apiVersion: v1
kind: Service
metadata:
  name: cep-nginx-clusterip-service
spec:
  selector:
    app: cep-nginx
  ports:
  - protocol: TCP
    port: 80           # Porta que o service vai expor
    targetPort: 8080   # Porta do container (do deployment)
  type: ClusterIP
