apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-service-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cep-nginx
  template:
    metadata:
      labels:
        app: cep-nginx
    spec:
      containers:
      - name: cep-nginx
        image: wesleyab/cep_service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
