name: Docker Image CepService CI

on:
  workflow_run:
    workflows: ["Deploy AKS and Kubernetes Resources"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: resourceintex.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Services/CEPService/Dockerfile
          push: true
          tags: resourceintex.azurecr.io/cepservice:latest
