name: CD - Deploy Infra and App AWS

on:
  push:
    branches: [main]

jobs:
  deploy-aws:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: sa-east-1
      EKS_CLUSTER_NAME: eks-terraform

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init (AWS)
        run: terraform -chdir=Terraform_AWS init

      - name: Terraform Plan (AWS)
        run: terraform -chdir=Terraform_AWS plan

      - name: Terraform Apply (AWS)
        run: terraform -chdir=Terraform_AWS apply -auto-approve

      - name: Configure kubectl to connect to EKS
        run: |
          aws eks --region us-east-1 update-kubeconfig --name eks-terraform

      - name: Deploy ingress-nginx no EKS
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
          kubectl rollout status deployment ingress-nginx-controller --namespace ingress-nginx --timeout=120s

      - name: Deploy app no EKS (Deployment, Service, Ingress)
        run: |
          kubectl apply -f Terraform_AWS/K8S/Deployment/cep.yaml
          kubectl apply -f Terraform_AWS/K8S/Service/cep.yaml
          kubectl apply -f Terraform_AWS/K8S/Ingress/cep.yaml

      - name: Check resources EKS
        run: |
          kubectl get pods -A
          kubectl get deployments -A
          kubectl get services -A
          kubectl get ingress -A

  destroy-on-failure:
    name: Destroy Infra if Deploy Fails
    runs-on: ubuntu-latest
    needs: deploy-aws
    if: failure() && needs.deploy-aws.result == 'failure'

    env:
      AWS_REGION: sa-east-1

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=Terraform_AWS init

      - name: Terraform Destroy
        run: terraform -chdir=Terraform_AWS destroy -auto-approve
