name: CI - Build and Push to AWS ECR

on:
  workflow_run:
    workflows: ["CD - Deploy Infra AWS"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: sa-east-1
      ECR_REPOSITORY: resourceintex

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push Docker image to ECR Teste
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Services/CEPService/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/resourceintex:latest
