# .github/workflows/ci.yml
name: CI - Build Docker Image

on:
  workflow_run:
    workflows: ["CD - Deploy Infra and App"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: resourceintex.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Services/CEPService/Dockerfile
          push: true
          tags: resourceintex.azurecr.io/cepservice:latest
